### ISSUE TITLE
Unable to connect

### ISSUE THREAD

**Issue by mgreenegit** [jlandersen/vscode-vsts-build-status#16]
I always get the error "unable to connect to account...".  I have the correct workspace settings and the Microsoft VSTS extension works without issue.  How would I collect information about why this is failing?

**Comment by jlandersen** [comment]
Hi

Can you confirm that in your settings you have the following settings:

- `vsts.account`
- `vsts.username`
- `vsts.project`
- `vsts.password`

For password, are you using PAT or user password? If using PAT, what scope does it have?

Thanks!

**Comment by jlandersen** [comment]
@mgreenegit just to follow up, do you still have this issue?

**Comment by jlandersen** [comment]
Closing for now - please reopen if you still experience issues.
