### ISSUE TITLE
Add option to open build URL in browser

### ISSUE THREAD

**Issue by lumaxis** [jlandersen/vscode-vsts-build-status#6]
Would be nice to have a command that directly opens a specific build's URL in the browser for the user to be able to inspect/act on the build in more detail.

**Comment by jlandersen** [comment]
Thanks for your interest in the extension :+1: 
I must admit, I kind of expected people to move to the official extensions:
https://marketplace.visualstudio.com/items?itemName=ms-vsts.team

Have you tried this one yet and is there any particular reason you would continue to use this one? In this case I will be happy to consider adding additional features to it.

**Comment by lumaxis** [comment]
@jlandersen Yes, I've tried it and am already using it in some projects. The problem is, the official extension does not work at all if your repository is not on VSTS.
We do however have some repos that are on other git servers and are only built & released through VSTS. For monitoring those builds your extension is superb 👌

**Comment by jlandersen** [comment]
Sorry for the late reply!

I have pushed 0.4.0 which adds another menu option for opening a build in the browser, similar to view logs
