### ISSUE TITLE
Stream running build's log into VS Code

### ISSUE THREAD

**Issue by lumaxis** [jlandersen/vscode-vsts-build-status#7]
Basically mirror the website's behavior that shows a "real-time" view of the running build's log output.
After initial investigation, it appears that is not possible with the current set of VSTS's public APIs. Might be worth filing a feature request with them?

**Comment by jlandersen** [comment]
I will look into a way of doing this - if all things fail, a solution could be to continuously get the logs until the build is finished

**Comment by jlandersen** [comment]
I just pushed 0.5.0 which supports this. I will work on optimizing it a bit, but the feature itself works.

**Comment by lumaxis** [comment]
Woah, nice! Thanks you ☺️
